Update README.md
Electric-Coin-Company/zcash-light-client-ffi pull request #140
Opened 2024-06-03 22:37 UTC by y4ssi

2024-06-05 00:19 UTC, str4d requested changes

2024-06-05 00:19 UTC, str4d commented on README.md
> +* MIT license (LICENSE-MIT or http://opensource.org/licenses/MIT)
This entire paragraph can be deleted; `orchard` is now no different to our other dependencies.

2024-08-10 01:19 UTC, nuttycom approved these changes
ACK

2024-08-10 01:19 UTC, merged

2024-08-10 20:59 UTC, daira reviewed
Post-hoc ACK